'use client'

import { useSearchParams } from 'next/navigation'
import { Suspense } from 'react'

function PolicyContent() {
  const searchParams = useSearchParams()
  
  // 从 URL 获取数据，如果没有就显示默认值
  const appName = searchParams.get('name') || 'Your App'
  const email = searchParams.get('email') || 'support@example.com'
  const date = searchParams.get('date') || new Date().toLocaleDateString()
  const url = searchParams.get('url')

  return (
    <div className="max-w-3xl mx-auto p-8 bg-white min-h-screen font-sans text-slate-800">
      <h1 className="text-3xl font-bold mb-2">Privacy Policy for {appName}</h1>
      <p className="text-sm text-gray-500 mb-8">Last Updated: {date}</p>

      <div className="space-y-6">
        <section>
          <h2 className="text-xl font-semibold mb-2">1. Introduction</h2>
          <p>
            Welcome to <strong>{appName}</strong>. We respect your privacy and are committed to protecting your personal data. 
            This privacy policy will inform you as to how we look after your personal data when you visit our application.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">2. Data Collection</h2>
          <p>
            We may collect, use, store and transfer different kinds of personal data about you which we have grouped together follows:
            <ul className="list-disc pl-5 mt-2 space-y-1">
              <li>Device information (Model, OS version)</li>
              <li>Usage data and analytics</li>
              <li>Crash logs</li>
            </ul>
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">3. Contact Us</h2>
          <p>
            If you have any questions about this privacy policy, please contact us at: 
            <a href={`mailto:${email}`} className="text-blue-600 ml-1 hover:underline">{email}</a>
          </p>
          {url && (
            <p className="mt-2">
              Official Website: <a href={url} className="text-blue-600 hover:underline">{url}</a>
            </p>
          )}
        </section>
      </div>
      
      <footer className="mt-20 pt-8 border-t text-center text-xs text-gray-400">
        Generated by Indie Privacy Generator
      </footer>
    </div>
  )
}

export default function PolicyPage() {
  return (
    <Suspense fallback={<div>Loading policy...</div>}>
      <PolicyContent />
    </Suspense>
  )
}